version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-petcare
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petcare_db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
